INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('G', NULL, 'Gemüse');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMi', 'G', 'Mittelzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiAMARANTH ', 'GMi', 'Amaranth ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiBETE ', 'GMi', 'Bete ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiCHILI ', 'GMi', 'Chili ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiFENCHEL ', 'GMi', 'Fenchel ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiKOHLRABI ', 'GMi', 'Kohlrabi ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiLAUCHZWIEBEL ', 'GMi', 'Lauchzwiebel ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiMANGOLD ', 'GMi', 'Mangold ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiMÖHRE ', 'GMi', 'Möhre ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiPAPRIKA ', 'GMi', 'Paprika ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiPASTINAKE ', 'GMi', 'Pastinake ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiPFEFFERONI ', 'GMi', 'Pfefferoni ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiRETTICH ', 'GMi', 'Rettich ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiSALAT ', 'GMi', 'Salat ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiSCHWARZWURZEL ', 'GMi', 'Schwarzwurzel ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GMiSPINAT ', 'GMi', 'Spinat ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GSc', 'G', 'Schwachzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GScBOHNE ', 'GSc', 'Bohne ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GScERBSE ', 'GSc', 'Erbse ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GScMAIRÜBE ', 'GSc', 'Mairübe ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GScRADIESCHEN ', 'GSc', 'Radieschen ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GScSALAT ', 'GSc', 'Salat ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GSt', 'G', 'Starkzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStANDENBEERE ', 'GSt', 'Andenbeere ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStAUBERGINE ', 'GSt', 'Aubergine ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStBLUMENKOHL ', 'GSt', 'Blumenkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStBROKKOLI ', 'GSt', 'Brokkoli ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStCHINAKOHL ', 'GSt', 'Chinakohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStGRÜNKOHL ', 'GSt', 'Grünkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStGURKE ', 'GSt', 'Gurke ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStKÜRBIS ', 'GSt', 'Kürbis ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStLAUCH ', 'GSt', 'Lauch ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStMELONE ', 'GSt', 'Melone ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStPALMKOHL ', 'GSt', 'Palmkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStROSENKOHL ', 'GSt', 'Rosenkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStROTKOHL ', 'GSt', 'Rotkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStSELLERIE ', 'GSt', 'Sellerie ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStTOMATE ', 'GSt', 'Tomate ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStWEIßKOHL ', 'GSt', 'Weißkohl ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStWIRSING ', 'GSt', 'Wirsing ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStZUCCHINI ', 'GSt', 'Zucchini ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('GStZUCKERMAIS ', 'GSt', 'Zuckermais ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('K', NULL, 'Kräuter');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KMi', 'K', 'Mittelzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KMiPETERSILIE ', 'KMi', 'Petersilie ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KSc', 'K', 'Schwachzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScBASILIKUM ', 'KSc', 'Basilikum ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScBRUNNENKRESSE', 'KSc', 'Brunnenkresse');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScDILL ', 'KSc', 'Dill ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScKNOBLAUCHSRAUKE', 'KSc', 'Knoblauchsrauke');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScKORIANDER', 'KSc', 'Koriander');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('KScLAUCH-HELLERKRAUT', 'KSc', 'Lauch-Hellerkraut');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('P', NULL, 'Pflanzgut');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PMi', 'P', 'Mittelzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PMiKNOBLAUCH ', 'PMi', 'Knoblauch ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PMiKNOLLIGER ', 'PMi', 'Knolliger ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PMiSCHALOTTE ', 'PMi', 'Schalotte ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PMiZWIEBEL ', 'PMi', 'Zwiebel ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PSc', 'P', 'Schwachzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PScTOPINAMBUR ', 'PSc', 'Topinambur ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PSt', 'P', 'Starkzehrer');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PStKARTOFFEL ', 'PSt', 'Kartoffel ');
INSERT INTO [Kategorie] ([KatID], [OberKatID], [Name]) VALUES	 ('PStSÜßKARTOFFEL ', 'PSt', 'Süßkartoffel ');